//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KombiCim.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CombiLog
    {
        public int Id { get; set; }
        public string DeviceId { get; set; }
        public bool State { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
