//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KombiCim.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinTemperature
    {
        public int Id { get; set; }
        public double Value { get; set; }
        public int LocationId { get; set; }
        public int ProfileId { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public Nullable<int> Hour { get; set; }
        public Nullable<int> Minute { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> DisabledAt { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
