//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KombiCim.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfilePreference
    {
        public int Id { get; set; }
        public int ProfileId { get; set; }
        public string DeviceId { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public Nullable<int> Hour { get; set; }
        public Nullable<int> Minute { get; set; }
        public Nullable<int> ActiveProfileId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool Active { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
