version: '3.4'

services:
  kombicim.arduino:
    image: ${DOCKER_REGISTRY-}kombicimarduino
    build:
      context: .
      dockerfile: Kombicim.Arduino/Dockerfile
    restart: always
    ports:
      - "7777:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  kombicim.mobile:
    image: ${DOCKER_REGISTRY-}kombicimmobile
    build:
      context: .
      dockerfile: Kombicim.Mobile/Dockerfile
    restart: always
    ports:
      - "8888:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production